name: Post JMA Weather to Discord

on:
  schedule:
    - cron: '30 3 * * *'  # 日本時間12:30（UTC 3:30）
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python post_weather.py
